//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.13 at 12:06:21 AM EST 
//


package org.example.carmodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.carmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Car_QNAME = new QName("http://www.example.org/CarModel", "car");
    private final static QName _Fleet_QNAME = new QName("http://www.example.org/CarModel", "fleet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.carmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Fleet }
     * 
     */
    public Fleet createFleet() {
        return new Fleet();
    }

    /**
     * Create an instance of {@link Car }
     * 
     */
    public Car createCar() {
        return new Car();
    }

    /**
     * Create an instance of {@link Owner }
     * 
     */
    public Owner createOwner() {
        return new Owner();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Car }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/CarModel", name = "car")
    public JAXBElement<Car> createCar(Car value) {
        return new JAXBElement<Car>(_Car_QNAME, Car.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fleet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/CarModel", name = "fleet")
    public JAXBElement<Fleet> createFleet(Fleet value) {
        return new JAXBElement<Fleet>(_Fleet_QNAME, Fleet.class, null, value);
    }

}
